language: cpp

compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8
env: COMPILER=clang++-3.8

before_script:
  - sudo apt-get update -q
  - sudo apt-get install libboost-all-dev libgsl0-dev

script: make test
